{
 "title": "M3Query Details",
 "tags": [ "disable-sync" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "source",
    "query": "label_values(coordinator_fetch_success,source)"
   }
  ]
 },
 "panels": [
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max Datapoints",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    { "expr": "coordinator_max_datapoints", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_fetch_success{source=\"$source\"}[1m])) by (source)",
     "legendFormat": "fetch_success"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_fetch_errors{source=\"$source\"}[1m])) by (source,code)",
     "legendFormat": "errors_per_second-{{code}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(coordinator_fetch_success_latency{source=\"$source\", quantile=\"0.99\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "avg(coordinator_fetch_success_latency{source=\"$source\", quantile=\"0.95\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "avg(coordinator_fetch_success_latency{source=\"$source\", quantile=\"0.75\"})",
     "legendFormat": "p75"
    }
   ]
  }
 ]
}